# Copyright 2014-now Equitania Software GmbH - Pforzheim - Germany
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

import copy
import os

from dotenv import load_dotenv

import odoo_report_helper.exceptions as exceptions
import odoo_report_helper.utils as utils

from . import eq_odoo_connection, eq_report
from .lang_utils import normalize_language_code, normalize_name_dict
from .logging_config import get_logger

logger = get_logger(__name__)

ENV_TEMPLATE = """# Odoo Fast Report Mapper - Environment Configuration
# Generated by: odoo-fr-mapper --init
# SECURITY: Never commit this .env file to version control!

# Odoo Server Connection (REQUIRED)
ODOO_URL=https://your-odoo-instance.com
ODOO_PORT=443
ODOO_USER=admin
ODOO_PASSWORD=your_password
ODOO_DATABASE=your_database

# Report Configuration (REQUIRED)
# Primary language for report names (Odoo locale code)
# Examples: de_DE, en_US, fr_FR, de_CH
# Legacy values 'ger' and 'eng' are still supported
ODOO_LANGUAGE=de_DE

# Workflow Configuration (OPTIONAL)
# Collect YAML from Odoo instead of mapping (True/False)
ODOO_COLLECT_YAML=False

# Disable QWeb reports after mapping (True/False)
ODOO_DISABLE_QWEB=True

# Operation mode: 0=Mapping only, 1=Testing only, 2=Mapping and Testing
ODOO_WORKFLOW=0
"""


def generate_env_template(target_dir=None):
    """
    Generate .env template file in target directory.

    Args:
        target_dir: Directory to create .env file in. Defaults to current working directory.

    Returns:
        Path to created .env file.

    Raises:
        FileExistsError: If .env file already exists in target directory.
    """
    if target_dir is None:
        target_dir = os.getcwd()

    env_file = os.path.join(target_dir, ".env")

    if os.path.exists(env_file):
        raise FileExistsError(f".env file already exists at: {env_file}")

    with open(env_file, "w", encoding="utf-8") as f:
        f.write(ENV_TEMPLATE)

    logger.info(f"Generated .env template at: {env_file}")
    return env_file


def create_report_object_from_yaml_object(yaml_object):
    """
    Create EqReport object from yaml_object
    :param: yaml_object
    :return: EqReport object
    """
    # Normalize legacy language keys (ger/eng) to Odoo locale codes (de_DE/en_US)
    name_dict = normalize_name_dict(yaml_object["name"])
    # Normalize print_report_name dict keys if it's a per-language dict
    print_report_name = yaml_object["print_report_name"]
    if isinstance(print_report_name, dict):
        print_report_name = normalize_name_dict(print_report_name)
    # Normalize attachment dict keys if it's a per-language dict
    attachment = yaml_object["attachment"]
    if isinstance(attachment, dict):
        attachment = normalize_name_dict(attachment)
    report = eq_report.EqReport(
        name_dict,
        yaml_object["report_name"],
        yaml_object["report_type"],
        yaml_object["report_model"],
        yaml_object.get("company_id", False),
        yaml_object["eq_export_type"],
        print_report_name,
        attachment,
        yaml_object["eq_ignore_images"],
        yaml_object["eq_handling_html_fields"],
        yaml_object["multi"],
        yaml_object["attachment_use"],
        yaml_object["eq_print_button"],
        yaml_object["dependencies"],
        yaml_object["report_fields"],
        yaml_object["calculated_fields"],
        yaml_object["eq_multiprint"],
    )
    return report


def create_odoo_connection_from_yaml_object(yaml_object):
    """
    Create EqOdooConnection object from yaml_object
    :param: yaml_object
    :return: EqOdooConnection object
    """
    eq_odoo_connection_object = eq_odoo_connection.EqOdooConnection(
        normalize_language_code(yaml_object["Server"]["language"]),
        (yaml_object["Server"].get("collect_yaml", False)),
        (yaml_object["Server"].get("disable_qweb", True)),
        yaml_object["Server"].get("workflow", 0),
        yaml_object["Server"]["url"],
        yaml_object["Server"]["port"],
        yaml_object["Server"]["user"],
        yaml_object["Server"]["password"],
        yaml_object["Server"]["database"],
    )
    return eq_odoo_connection_object


def convert_all_yaml_objects(yaml_objects: list, converting_function):
    """
    Convert list of yaml_objects through a converting function
    :param: list of yaml_objects
    :param: Function with which the yaml_objects should be converted
    :return: list of objects
    """
    local_object_list = []
    for yaml_object in yaml_objects:
        local_object = converting_function(yaml_object)
        local_object_list.append(local_object)
    return local_object_list


def build_reports_from_yaml_objects(yaml_objects):
    """
    Convert raw YAML dicts to EqReport objects, handling multi-company expansion.

    A YAML dict with company_id: [1, 3, 5] is expanded into three separate
    EqReport objects, each with a single company_id.

    :param: yaml_objects: list of parsed YAML dicts
    :return: list of EqReport objects
    """
    filtered_yaml_report_objects = []
    for yaml_report_object in yaml_objects:
        if yaml_report_object.get("company_id") and len(yaml_report_object.get("company_id")) > 1:
            company_ids = yaml_report_object.get("company_id")
            del yaml_report_object["company_id"]
            for company_id in company_ids:
                temp_yaml_report_object = copy.deepcopy(yaml_report_object)
                temp_yaml_report_object["company_id"] = [company_id]
                filtered_yaml_report_objects.append(temp_yaml_report_object)
        else:
            filtered_yaml_report_objects.append(yaml_report_object)
    return convert_all_yaml_objects(filtered_yaml_report_objects, create_report_object_from_yaml_object)


def list_yaml_reports(path):
    """
    List all YAML report files with metadata for interactive display.

    :param: path: path to yaml files directory
    :return: list of dicts with keys: filename, report_name, model, yaml_object
    """
    yaml_items = utils.parse_yaml_folder_with_filenames(path)
    result = []
    for filename, yaml_obj in yaml_items:
        result.append(
            {
                "filename": filename,
                "report_name": yaml_obj.get("report_name", "N/A"),
                "model": yaml_obj.get("report_model", "N/A"),
                "yaml_object": yaml_obj,
            }
        )
    return result


def collect_all_reports(path):
    """
    Get all yaml objects from path and convert them into report objects
    :param: path to yaml files
    :return: list of report objects
    """
    try:
        yaml_report_objects = utils.parse_yaml_folder(path)
        return build_reports_from_yaml_objects(yaml_report_objects)
    except FileNotFoundError as ex:
        raise exceptions.PathDoesNotExitError("ERROR: Please check your Path" + " " + str(ex)) from ex


def create_connection_from_env(env_path=None):
    """
    Create EqOdooConnection object from environment variables (.env file).

    Args:
        env_path: Optional path to .env file. If None, searches in current directory.
                  Can be either a directory path or full path to .env file.

    Required environment variables:
        ODOO_URL: Odoo server URL (e.g., https://odoo.example.com)
        ODOO_PORT: Odoo server port (e.g., 443 for HTTPS, 8069 for HTTP)
        ODOO_USER: Odoo username
        ODOO_PASSWORD: Odoo password
        ODOO_DATABASE: Odoo database name
        ODOO_LANGUAGE: Primary language for report names (Odoo locale code, e.g. de_DE, en_US; legacy 'ger'/'eng' supported)

    Optional environment variables:
        ODOO_COLLECT_YAML: Collect YAML from Odoo (default: False)
        ODOO_DISABLE_QWEB: Disable QWeb reports (default: True)
        ODOO_WORKFLOW: Workflow mode (0=mapping, 1=testing, 2=both, default: 0)

    :return: EqOdooConnection object
    :raises: ValueError if required environment variables are missing
    """
    # Determine .env file path
    if env_path:
        # If env_path is a directory, append .env filename
        if os.path.isdir(env_path):
            dotenv_path = os.path.join(env_path, ".env")
        else:
            dotenv_path = env_path

        if not os.path.exists(dotenv_path):
            logger.error(f".env file not found at: {dotenv_path}")
            raise ValueError(f".env file not found at: {dotenv_path}")

        logger.info(f"Loading .env from: {dotenv_path}")
        load_dotenv(dotenv_path=dotenv_path)
    else:
        # Load .env file from current working directory
        cwd_env = os.path.join(os.getcwd(), ".env")
        if os.path.exists(cwd_env):
            logger.info(f"Loading .env from: {cwd_env}")
            load_dotenv(dotenv_path=cwd_env)
        else:
            logger.warning(f".env not found in current directory: {os.getcwd()}")
            logger.info("Trying python-dotenv auto-discovery...")
            load_dotenv()

    # Required variables
    required_vars = {
        "ODOO_URL": "url",
        "ODOO_PORT": "port",
        "ODOO_USER": "user",
        "ODOO_PASSWORD": "password",
        "ODOO_DATABASE": "database",
        "ODOO_LANGUAGE": "language",
    }

    # Check for missing required variables
    missing_vars = [var for var in required_vars if not os.getenv(var)]
    if missing_vars:
        error_msg = f"Missing required environment variables: {', '.join(missing_vars)}"
        logger.error(error_msg)
        logger.info("Please create a .env file based on .env.example")
        raise ValueError(error_msg)

    # Get required values
    url = os.getenv("ODOO_URL")
    try:
        port = int(os.getenv("ODOO_PORT"))
        if port < 1 or port > 65535:
            raise ValueError(f"Port must be between 1 and 65535, got: {port}")
    except (ValueError, TypeError) as e:
        raise ValueError(f"Invalid ODOO_PORT value: {os.getenv('ODOO_PORT')} — {e}") from e
    user = os.getenv("ODOO_USER")
    password = os.getenv("ODOO_PASSWORD")
    database = os.getenv("ODOO_DATABASE")
    language = normalize_language_code(os.getenv("ODOO_LANGUAGE"))

    # Get optional values with defaults
    collect_yaml = os.getenv("ODOO_COLLECT_YAML", "False").lower() in (
        "true",
        "1",
        "yes",
    )
    disable_qweb = os.getenv("ODOO_DISABLE_QWEB", "True").lower() in (
        "true",
        "1",
        "yes",
    )
    workflow = int(os.getenv("ODOO_WORKFLOW", "0"))

    logger.info(f"Creating connection to {database}@{url}:{port}")
    logger.debug(
        f"Configuration: language={language}, workflow={workflow}, collect_yaml={collect_yaml}, disable_qweb={disable_qweb}"
    )

    # Create connection object
    # EqOdooConnection expects: language, collect_yaml, disable_qweb, workflow, url, port, username, password, database
    connection = eq_odoo_connection.EqOdooConnection(
        language,
        collect_yaml,
        disable_qweb,
        workflow,
        url,
        port,
        user,  # Will be passed as 'username' to parent class
        password,
        database,
    )

    return connection


def collect_all_connections(path):
    """
    DEPRECATED: Get all yaml objects from path and convert them into connection objects.

    This function is deprecated and maintained only for backwards compatibility.
    Use create_connection_from_env() instead for better security.

    :param: path to yaml files
    :return: list of connection objects
    """
    logger.warning("collect_all_connections() is deprecated. Use create_connection_from_env() instead.")
    try:
        yaml_connection_objects = utils.parse_yaml_folder(path)
        eq_connection_objects = convert_all_yaml_objects(
            yaml_connection_objects, create_odoo_connection_from_yaml_object
        )
        return eq_connection_objects
    except FileNotFoundError as ex:
        raise exceptions.PathDoesNotExitError("ERROR: Please check your Path" + " " + str(ex)) from ex
