---
# Server configuration
Server:
  url: https://odoo.com                             # URL to Odoo - for localhost write http://localhost
  port: 443                                         # Port of Odoo - Remote over SSL write 443 - for localhost write 8069 or other Odoo port
  user: admin                                       # Your Odoo admin-user or user with setting rights
  password: pw                                      # Password for the user
  database: db                                      # Name of the Odoo database
  delete_old_reports: True                          # Cleanup old Fast-Report Settings in Odoo systems
  # This entry depends on your report yaml files
  language: ger                                     # Name settings in Odoo system. With "en" names will be English depends on the YAML-file for reports
  # The following configuration parameters are not mandatory, if not included in the configuration then the default values are used
  collect_yaml: False                               # Yaml collection - this will disable mapping of report. The default is False.
  disable_qweb: True                                # Disable QWeb reports. The default is True.
  workflow: 0                                       # Mapper workflow if the parameter collect_yaml is False. 0: Only mapping(default) 1: Only testing 2: Mapping and Testing